config/routes.rb
Lifesupport::Application.routes.draw do

  scope "/devdashboard" do
    
    get "user/login"
    post "user/process_login"
    post "user/logout"
    post "llamadas/new"
    
    match 'login' => 'user#login'
    match 'logout' => 'user#logout'
    match 'process_login' => 'user#process_login'
        
    root :to => "llamadas#index"
    resources :clientes
    resources :llamadas
    resources :destinos
    resources :statusllamadas
    resources :servicios
    resources :ambulances
    resources :prioridads
    resources :usuarios
    resources :users
    
    resources :llamadas do
      resources :hojadeatencions, :only => [:update, :index]
      resources :bitacoras, :only => [:index]
    end
    
  end

end

app/models/ambulance.rb
class Ambulance < ActiveRecord::Base
    has_one :llamada
  # attr_accessible :title, :body
end

app/models/bitacora_llamada.rb
class BitacoraLlamada < ActiveRecord::Base
  belongs_to :llamada
  belongs_to :statusllamada
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :llamadas
  
  attr_accessible :user_type, :cp, :cliente, :telefono, :ciudad, 
                  :padecimientos, :razon_social, :direccion, :estado, 
                  :afiliado, :afiliacion, :fecha_nacimiento, :colonia, 
                  :tipo_sanguineo, :alergias, :nombre, :rfc, :entre_calles, 
                  :avisar, :servicio_medico, :parent_id
  
  @@results_per_page = 10
  
  def self.search(search, page)
    page = page.to_i
    if page == 0 then 
      page = 1
    end
    
    offset = ((page * @@results_per_page) - @@results_per_page)
    
    if search
      find(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"], :limit => @@results_per_page, :offset => offset)
    else
      find(:all, :limit => @@results_per_page, :offset => offset)
    end
  end
  
  def self.num_rows(search)
    num_rows = count(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"])
    num_pages = (num_rows/@@results_per_page.to_f).ceil
    data = Hash.new
    data['rows'] = num_rows
    data['pages'] = num_pages
    return data
  end
  
  def self.get_afiliados(parent_id)
    find(:all, :conditions => ["status = 'active' and parent_id = ?", parent_id], :limit => 30)
  end

end

app/models/destino.rb
class Destino < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/hojadeatencion.rb
class Hojadeatencion < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :llamada
  has_many :signosvitale
end

app/models/llamada.rb
class Llamada < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :prioridad
  belongs_to :servicio
  belongs_to :statusllamada
  belongs_to :destino
  belongs_to :ambulance
  has_many   :bitacorallamada
  has_many   :hojadeatencion
  
  #accepts_nested_attributes_for :hojadeatencion
  
  validates :reporta, :reporte, :ubicacion, :presence => true
  
  before_save do |llamada|
      if llamada.id then
          original = Llamada.find(llamada.id)
          if original.statusllamada_id != llamada.statusllamada_id then
              BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
          end
      end
  end
  
  after_create do |llamada|
      BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
      @hoja = Hojadeatencion.create(:llamada_id => llamada.id)
      # I know this is ugly but I promess to fix it when I have more time
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
  end
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/signosvitale.rb
class Signosvitale < ActiveRecord::Base
  # attr_accessible :title, :body
    belongs_to :hojadeatencion
end

app/models/statusllamada.rb
class Statusllamada < ActiveRecord::Base
  has_many :llamada
  has_many :bitacorallamada
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  attr_accessible :username, :password

  def self.authenticate(username, password)
    find(:first, :conditions => ["username = ? and password = ?", "#{username}", "#{password}"])
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :authenticate
  
  def index
      $do = params[:do]
      search = params[:search]
      
      #show/edit
      if $do == 'show' then
          redirect_to :action => 'show', :id => params[:id]
      elsif search then
          $do = 'results'
          data = Cliente.num_rows(params[:search])
          $num_rows = data['rows']
          $num_pages = data['pages']
          @clientes = Cliente.search(params[:search], params[:page])
      end
  end  

  def show
      id = params[:id]
      if params[:afiliado_id] then
        id = params[:afiliado_id]
      end
      @cliente = Cliente.find(id)
      address = @cliente.direccion + ", " + @cliente.colonia + ", " + @cliente.ciudad + ", " + @cliente.estado + ", Mexico"
      @map = Geocoder.search(address)
      if params[:afiliado_id].nil? then @afiliado = Cliente.get_afiliados(id) end
  end

  def new
      @cliente = Cliente.new
      $is_afiliado = params[:afiliado]
      $cid = params[:id]
  end
  
  def create
      @cliente = Cliente.new(params[:cliente])
      @cliente.save
      
      flash[:notice] = "EL Cliente fue creado."
      redirect_to @cliente
  end

  def update
      @cliente = Cliente.find(params[:id])
      @cliente.update_attributes(params[:cliente])
      
      flash[:notice] = "EL Cliente fue editado."
      redirect_to @cliente
  end

  def destroy
      Cliente.update_all("status = 'deleted'", ["id = ? or parent_id = ?", params[:id], params[:id]])
      
      flash[:notice] = "EL Cliente fue Eliminado."
      redirect_to :action => 'index'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
    @user = User.new
  end
  
  def process_login
    if user = User.authenticate(params[:username], params[:password])
        session[:id] = user.id
        session[:user_name] = user.nombre
        redirect_to session[:return_to] || root_url
    else
        flash[:error] = 'Invalid login.' 
        redirect_to :action => 'login'
      end
  end
  
  def logout
    reset_session
    session[:id] = nil
    flash[:notice] = "Logged out!"
    redirect_to :action => 'login' 
  end
end

app/helpers/ambulances_helper.rb
module AmbulancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/destinos_helper.rb
module DestinosHelper
end

app/helpers/llamadas_helper.rb
module LlamadasHelper
end

app/helpers/prioridads_helper.rb
module PrioridadsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clientes/_afiliado.html.erb
<h2>Afiliados</h2>
<ul>
  <% @afiliado.each do |afiliado| %>
  <li>
    <a class="profile-link" href="../?do=show&amp;afiliado_id=<%= afiliado.id %>">
      <i class="custom cus-user"></i><%= afiliado.nombre %> (<%= afiliado.id %>)
    </a>
  </li>
  <% end %>
</ul>

app/views/clientes/_afiliados.html.erb
<h2>Afiliados</h2>
<ul>
  <% @afiliado.each do |afiliado| %>
  <li>
    <a class="profile-link" href="?afiliado_id=<%= afiliado.id %>">
      <i class="custom cus-user"></i><%= afiliado.nombre %> (<%= afiliado.id %>)
    </a>
  </li>
  <% end %>
</ul>

app/views/clientes/_estados.html.erb
 <select name="cliente[estado]" id="estado">
      <option value="">Seleccione una opción</option>
      <option value="AGUASCALIENTES" <%= if @cliente.estado == "AGUASCALIENTES" then 'selected' end %>AGUASCALIENTES</option>
      <option value="BAJA CALIFORNIA">BAJA CALIFORNIA</option>
      <option value="BAJA CALIFORNIA SUR">BAJA CALIFORNIA SUR</option>
      <option value="CAMPECHE">CAMPECHE</option>
      <option value="CHIAPAS">CHIAPAS</option>
      <option value="CHIHUAHUA">CHIHUAHUA</option>
      <option value="COAHUILA DE ZARAGOZA" <%= if @cliente.estado == "COAHUILA DE ZARAGOZA" then 'selected' end %>>COAHUILA DE ZARAGOZA</option>
      <option value="COLIMA">COLIMA</option>
      <option value="DISTRITO FEDERAL">DISTRITO FEDERAL</option>
      <option value="DURANGO">DURANGO</option>
      <option value="ESTADO DE MEXICO">ESTADO DE MEXICO</option>
      <option value="GUANAJUATO">GUANAJUATO</option>
      <option value="GUERRERO">GUERRERO</option>
      <option value="HIDALGO">HIDALGO</option>
      <option value="JALISCO">JALISCO</option>
      <option value="MICHOACAN">MICHOACAN DE OCAMPO</option>
      <option value="MORELOS">MORELOS</option>
      <option value="NAYARIT">NAYARIT</option>
      <option value="NUEVO LEON">NUEVO LEON</option>
      <option value="OAXACA">OAXACA</option>
      <option value="PUEBLA">PUEBLA</option>
      <option value="QUERETARO">QUERETARO DE ARTEAGA</option>
      <option value="QUINTANA ROO">QUINTANA ROO</option>
      <option value="SAN LUIS POTOSI">SAN LUIS POTOSI</option>
      <option value="SINALOA">SINALOA</option>
      <option value="SONORA">SONORA</option>
      <option value="TABASCO">TABASCO</option>
      <option value="TAMAULIPAS">TAMAULIPAS</option>
      <option value="TLAXCALA">TLAXCALA</option>
      <option value="VERACRUZ">VERACRUZ DE IGNACIO DE LA LLAVE</option>
      <option value="YUCATAN">YUCATAN</option>
      <option value="ZACATECAS">ZACATECAS</option>
</select>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="span span4">
  <tr><td>
  <div class="field">
    <%= f.label "Nombre del Cliente:" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Teléfono:" %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label "Dirección:" %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label "Entre Calles:" %><br />
    <%= f.text_field :entre_calles %>
  </div>
  <div class="field">
    <%= f.label "Colonia:" %><br />
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label "Código Postal:" %><br />
    <%= f.text_field :cp %>
  </div>
  <div class="field">
    <%= f.label "Estado" %><br />
    <%= render 'estados' %>
    <!--<%= f.text_field :estado %>-->
  </div>
  <div class="field">
    <%= f.label "Ciudad:" %><br />
    <%= f.text_field :ciudad %>
  </div>
</div>
<div class="span span4">
  <div class="field">
    <%= f.label "Razón Social:" %><br />
    <%= f.text_field :razon_social %>
  </div>
  <div class="field">
    <%= f.label "RFC:" %><br />
    <%= f.text_field :rfc %>
  </div>
  <div class="field">
    <%= f.label "Avisar:" %><br />
    <%= f.text_field :avisar %>
  </div>
  <div class="field">
    <%= f.label "Servicio Médico:" %><br />
    <%= f.text_field :servicio_medico %>
  </div>
  <div class="field">
    <%= f.label "Afiliación:" %><br />
    <%= f.text_field :afiliacion %>
  </div>
  <div class="field">
    <%= f.label "Tipo Sanguíneo:" %><br />
    <%= f.text_field :tipo_sanguineo %>
  </div>
  <div class="field">
    <%= f.label "Fecha de Nacimiento(aaaa/mm/dd):" %><br />
    <%= f.text_field :fecha_nacimiento %>
  </div>
</div>
<div class="span span4">
  <div class="field">
    <%= f.label "Padecimientos:" %><br />
    <%= f.text_area :padecimientos %>
  </div>
  <div class="field">
    <%= f.label "Alergias:" %><br />
    <%= f.text_area :alergias %>
  </div>
    
      <% if $is_afiliado %>
        <%= f.hidden_field :parent_id, :value => $cid %>
        <%= f.hidden_field :user_type, :value => 'afiliado' %>
      <% end %>
      <div class="actions">
    <%= f.submit "Guardar", :class=>'btn' %>
  </div>
</div>
  
<% end %>

app/views/clientes/_results.html.erb
<%
current = params[:page].to_i
if current == 0 then 
      current = 1
end
anterior = current.to_i - 1
siguiente = current.to_i + 1
%>
Clientes : <%= $num_rows %>
<div class="pull-right">
   <% if anterior > 0 %>
     <%= link_to 'Anterior', "?search=#{params[:search]}&page=#{anterior}", :class => 'btn' %>
   <% end %>
   <%= current %> de <%= $num_pages %>
   <% if current <  $num_pages %>
     <%= link_to 'Siguiente', "?search=#{params[:search]}&page=#{siguiente}", :class => 'btn' %>
   <% end %>
</div>
<br/>
<ul>
  <% @clientes.each do |cliente| %>
  <li>
    <a class="profile-link" href="?do=show&id=<%= cliente.id %>">
      <%= '(afiliado)' if !cliente.parent_id.nil? %><%= cliente.nombre %> (<%= cliente.id %>)
    </a>
  </li>
  <% end %>
</ul>

app/views/clientes/_search.html.erb
<%= form_tag '', :method => 'get', :class => 'well form-search' do %>
    <span id="page-title" class="lead space-right"><a>Clientes</a></span>
    <%= text_field_tag :search, params[:search], :placeholder => 'escriba el criterio de búsqueda', :class => 'input-medium search-query' %>
    <!--<button type="submit" class="btn"><i class="icon-search"></i></button> -->
    <!--<button id="add-record" type="submit" class="btn"><i class="custom cus-add"></i></button> -->
    <%= submit_tag "Buscar", :name => nil %>
<% end %>

app/views/clientes/index.html.erb
<div class="pull-right">
        <%= link_to 'Crear Cliente', new_cliente_path, :class => 'btn' %>
</div>

<h2>Clientes</h2>

<% if $do == 'results'  %>

    <%= render 'search' %>
    <%= render 'results' %>

<% else %>
    <%= render 'search' %>

<%  end %>

app/views/clientes/new.html.erb
<div class="pull-right">
   <%= link_to 'Regresar', clientes_path, :class => 'btn' %>
</div>

<% if $is_afiliado %><h2>Crear afiliado - Membresia <%= $cid %></h1>
<% else %>           <h2>Crear cliente</h1>
<%  end %>

<div class="row"><%= render 'form' %></div>

app/views/clientes/show.html.erb
<div class="pull-right">
   <% if @cliente.parent_id.nil? %>
       <%= link_to 'Crear Afiliado', new_cliente_path(:afiliado => true, :id => @cliente.id), :class => 'btn' %>
   <% else %>
       <%= link_to 'Ver Cliente', "#{@cliente.parent_id}", :class => 'btn' %>
   <% end %>
   <%= link_to 'Eliminar', @cliente, :confirm => 'Seguro?', :method => :delete, :class => 'btn' %>
   <%= link_to 'Regresar', clientes_path, :class => 'btn' %>
</div>

<h2><%= @cliente.parent_id ? 'Afiliado: ' : 'Cliente: ' %><%= @cliente.nombre %></h2>

<div class="row">

<%= render 'form' %>

<% if !@afiliado.nil? and @afiliado.any? %>
  <div class="span span4"><%= render 'afiliados' %></div>
<% end %>

</div>
 <div style="min-height: 500px;"><br/><br/><%= render :partial => 'layouts/map' %></div>