config/routes.rb
Lifesupport::Application.routes.draw do

  scope "/devdashboard" do
    
    get "user/login"
    post "user/process_login"
    post "user/logout"
    post "llamadas/new"
    
    match 'login' => 'user#login'
    match 'logout' => 'user#logout'
    match 'process_login' => 'user#process_login'
        
    root :to => "llamadas#index"
    resources :clientes
    resources :llamadas
    resources :destinos
    resources :statusllamadas
    resources :servicios
    resources :ambulances
    resources :prioridads
    resources :usuarios
    resources :users
    
    resources :llamadas do
      resources :hojadeatencions, :only => [:update, :index]
      resources :bitacoras, :only => [:index]
    end
    
  end

end

app/models/ambulance.rb
class Ambulance < ActiveRecord::Base
    has_one :llamada
  # attr_accessible :title, :body
end

app/models/bitacora_llamada.rb
class BitacoraLlamada < ActiveRecord::Base
  belongs_to :llamada
  belongs_to :statusllamada
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :llamadas
  
  attr_accessible :user_type, :cp, :cliente, :telefono, :ciudad, 
                  :padecimientos, :razon_social, :direccion, :estado, 
                  :afiliado, :afiliacion, :fecha_nacimiento, :colonia, 
                  :tipo_sanguineo, :alergias, :nombre, :rfc, :entre_calles, 
                  :avisar, :servicio_medico, :parent_id
  
  @@results_per_page = 10
  
  def self.search(search, page)
    page = page.to_i
    if page == 0 then 
      page = 1
    end
    
    offset = ((page * @@results_per_page) - @@results_per_page)
    
    if search
      find(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"], :limit => @@results_per_page, :offset => offset)
    else
      find(:all, :limit => @@results_per_page, :offset => offset)
    end
  end
  
  def self.num_rows(search)
    num_rows = count(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"])
    num_pages = (num_rows/@@results_per_page.to_f).ceil
    data = Hash.new
    data['rows'] = num_rows
    data['pages'] = num_pages
    return data
  end
  
  def self.get_afiliados(parent_id)
    find(:all, :conditions => ["status = 'active' and parent_id = ?", parent_id], :limit => 30)
  end

end

app/models/destino.rb
class Destino < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/hojadeatencion.rb
class Hojadeatencion < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :llamada
  has_many :signosvitale
end

app/models/llamada.rb
class Llamada < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :prioridad
  belongs_to :servicio
  belongs_to :statusllamada
  belongs_to :destino
  belongs_to :ambulance
  has_many   :bitacorallamada
  has_many   :hojadeatencion
  
  #accepts_nested_attributes_for :hojadeatencion
  
  validates :reporta, :reporte, :ubicacion, :presence => true
  
  before_save do |llamada|
      if llamada.id then
          original = Llamada.find(llamada.id)
          if original.statusllamada_id != llamada.statusllamada_id then
              BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
          end
      end
  end
  
  after_create do |llamada|
      BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
      @hoja = Hojadeatencion.create(:llamada_id => llamada.id)
      # I know this is ugly but I promess to fix it when I have more time
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
  end
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/signosvitale.rb
class Signosvitale < ActiveRecord::Base
  # attr_accessible :title, :body
    belongs_to :hojadeatencion
end

app/models/statusllamada.rb
class Statusllamada < ActiveRecord::Base
  has_many :llamada
  has_many :bitacorallamada
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  attr_accessible :username, :password

  def self.authenticate(username, password)
    find(:first, :conditions => ["username = ? and password = ?", "#{username}", "#{password}"])
  end
end

app/controllers/hojadeatencions_controller.rb
class HojadeatencionsController < ApplicationController
  def index
    @llamada = Llamada.find(params[:llamada_id])
    #@hojadeatencion = @llamada.hojadeatencion.first
    @hojadeatencion = Hojadeatencion.where("llamada_id = #{params[:llamada_id]}").first
    @sv = Signosvitale.where("hojadeatencion_id = #{@hojadeatencion.id}")
  end
  
  def update
    @llamada = Llamada.find(params[:llamada_id])
    #@hojadeatencion = @llamada.hojadeatencion.build(params[:hojadeatencion])
    @hojadeatencion = Hojadeatencion.where("llamada_id = #{params[:llamada_id]}").first
    @hojadeatencion.update_attributes(params[:hojadeatencion])
    #@hojadeatencion.save
    #params[:sv].each do |psv|
    # I know this is fucking ugly I will fix this later
      @sv = Signosvitale.find(params[:sv]["0"]["id"])
      @sv.update_attributes(params[:sv]["0"])
      
      @sv = Signosvitale.find(params[:sv]["1"]["id"])
      @sv.update_attributes(params[:sv]["1"])
      
      @sv = Signosvitale.find(params[:sv]["2"]["id"])
      @sv.update_attributes(params[:sv]["2"])
    #end
    flash[:notice] = "Hoja de atencion Editada."
    redirect_to llamada_hojadeatencions_path(@llamada)
  end
end

app/helpers/ambulances_helper.rb
module AmbulancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/destinos_helper.rb
module DestinosHelper
end

app/helpers/hojadeatencions_helper.rb
module HojadeatencionsHelper
end

app/helpers/llamadas_helper.rb
module LlamadasHelper
end

app/helpers/prioridads_helper.rb
module PrioridadsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hojadeatencions/index.html.erb
<%= render :partial => 'llamadas/nav_menu' %>

<h2>Hoja de Atencion de Llamada</h2>

<%= form_for ([@llamada, @hojadeatencion], :method => :put, :url => llamada_hojadeatencion_path(@llamada, @hojadeatencion.id)) do |f| %>
<div class="span span4">
      <h3>Via Aerea</h3>
      <div class="field">
        Permeable: <br />
        <div class="field">
        <%= f.radio_button :permeable, 'si' %>SI Aspiracion<br/>
        <%= f.radio_button :permeable, 'no' %>NO Permeabilizacion Manual, Mecanica
      </div>
      </div>
      <h3>Ventilacion</h3>
      <div class="field">
        Saturacion Inicial<br />
        <%= f.text_field :saturacion_inicial %>
      </div>
      <div class="field">
        Saturacion Final  <br />
        <%= f.text_field :saturacion_final  %>
      </div>
      <h3>Circulacion</h3>
      <div class="field">
        Coloracion de piel<br />
        <%= f.text_field :coloracion_piel %>
      </div>
      <div class="field">
        Temperatura<br />
        <%= f.text_field :temperatura %>
      </div>
      <div class="field">
        Llenado Capilar<br />
        <%= f.text_field :llenado_capilar %>
      </div>
      <div class="field">
        Pulsos Perifericos<br />
        <%= f.text_field :pulsos_perifericos %>
      </div>    
 </div>

<div class="span span4">     
      <h3>Estado Neurologico</h3>
      <div class="field">
        Alerta<br />
        <%= f.text_field :en_alerta %>
      </div>
      <div class="field">
        Verbal<br />
        <%= f.text_field :en_verbal %>
      </div>
      <div class="field">
        Dolor<br />
        <%= f.text_field :en_dolor %>
      </div>
      <div class="field">
        Inconciencia<br />
        <%= f.text_field :en_inconciencia %>
      </div>
      <h3>Estado Conciencia</h3>
       <div class="field">
        Persona<br />
        <%= f.text_field :ec_persona %>
      </div>
      <div class="field">
        Lugar<br />
        <%= f.text_field :ec_lugar %>
      </div>
      <div class="field">
        Tiempo <br />
        <%= f.text_field :ec_tiempo  %>
      </div>
      <div class="field">
        Ocular<br />
        <%= f.text_field :ec_ocular  %>
      </div>
      <div class="field">
        Verbal<br />
        <%= f.text_field :ec_verbal  %>
      </div>
      <div class="field">
        Motora <br />
        <%= f.text_field :ec_motora  %>
      </div>
      <div class="field">
        Clasgow <br />
        <%= f.text_field :ec_clasgow    %>
      </div>
</div>

<div class="span span4">    
      <h3>Historia Clinica</h3>
      <div class="field">
        Alergia<br />
        <%= f.text_field :hc_alergia %>
      </div>
      <div class="field">
        Patologia<br />
        <%= f.text_field :hc_patologia %>
      </div>
      <h3>Exploracion Fisica</h3>
      <div class="field">
        Dolor<br />
        <%= f.text_field :dolor %>
      </div>
      <h3>Impresion Diagnostica</h3>
      <div class="field">
        Indicaciones<br />
        <%= f.text_field :indicaciones %>
      </div>
      <div class="field">
        Manejo<br />
        <%= f.text_field :manejo %>
      </div>
      <div class="field">
        Medico<br />
        <%= f.text_field :medico %>
      </div>
</div>
<div class="span span4">
<h3>Signos Vitales</h3>
      <input type="hidden" name="sv[0][id]" value="<%= @sv[0].id %>">
      <input type="hidden" name="sv[1][id]" value="<%= @sv[1].id %>">
       <input type="hidden" name="sv[2][id]" value="<%= @sv[2].id %>">
      <table class="littlefields">
        <tr><td>Hora</td><td>FC</td><td>FR</td><td>T/A</td><td>TEMP</td></tr>
        <tr>
          <td><input type="text" name="sv[0][hora]" size="3" style="width:46px;" value="<%= @sv[0].hora %>"></td>
          <td><input type="text" name="sv[0][fc]" size="3" value="<%= @sv[0].fc %>"></td>
          <td><input type="text" name="sv[0][fr]" size="3" value="<%= @sv[0].fr %>"></td>
          <td><input type="text" name="sv[0][ta]" size="3" value="<%= @sv[0].ta %>"></td>
          <td><input type="text" name="sv[0][temp]" size="3" value="<%= @sv[0].temp %>"></td>
        </tr>
        <tr>
          <td><input type="text" name="sv[1][hora]" size="3" style="width:46px;" value="<%= @sv[1].hora %>" ></td>
          <td><input type="text" name="sv[1][fc]" size="3" value="<%= @sv[1].fc %>"></td>
          <td><input type="text" name="sv[1][fr]" size="3" value="<%= @sv[1].fr %>"></td>
          <td><input type="text" name="sv[1][ta]" size="3" value="<%= @sv[1].ta %>"></td>
          <td><input type="text" name="sv[1][temp]" size="3" value="<%= @sv[1].temp %>"></td>
        </tr>
        <tr>
          <td><input type="text" name="sv[2][hora]" size="3" style="width:46px;" value="<%= @sv[2].hora %>"></td>
          <td><input type="text" name="sv[2][fc]" size="3" value="<%= @sv[2].fc %>"></td>
          <td><input type="text" name="sv[2][fr]" size="3" value="<%= @sv[2].fr %>"></td>
          <td><input type="text" name="sv[2][ta]" size="3" value="<%= @sv[2].ta %>"></td>
          <td><input type="text" name="sv[2][temp]" size="3" value="<%= @sv[2].temp %>"></td>
        </tr>
      </table>
      <%= f.submit :Guardar, :class => 'btn' %>
      </div>
      
<% end %>