config/routes.rb
Lifesupport::Application.routes.draw do

  scope "/devdashboard" do
    
    get "user/login"
    post "user/process_login"
    post "user/logout"
    post "llamadas/new"
    
    match 'login' => 'user#login'
    match 'logout' => 'user#logout'
    match 'process_login' => 'user#process_login'
        
    root :to => "llamadas#index"
    resources :clientes
    resources :llamadas
    resources :destinos
    resources :statusllamadas
    resources :servicios
    resources :ambulances
    resources :prioridads
    resources :usuarios
    resources :users
    
    resources :llamadas do
      resources :hojadeatencions, :only => [:update, :index]
      resources :bitacoras, :only => [:index]
    end
    
  end

end

app/models/ambulance.rb
class Ambulance < ActiveRecord::Base
    has_one :llamada
  # attr_accessible :title, :body
end

app/models/bitacora_llamada.rb
class BitacoraLlamada < ActiveRecord::Base
  belongs_to :llamada
  belongs_to :statusllamada
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :llamadas
  
  attr_accessible :user_type, :cp, :cliente, :telefono, :ciudad, 
                  :padecimientos, :razon_social, :direccion, :estado, 
                  :afiliado, :afiliacion, :fecha_nacimiento, :colonia, 
                  :tipo_sanguineo, :alergias, :nombre, :rfc, :entre_calles, 
                  :avisar, :servicio_medico, :parent_id
  
  @@results_per_page = 10
  
  def self.search(search, page)
    page = page.to_i
    if page == 0 then 
      page = 1
    end
    
    offset = ((page * @@results_per_page) - @@results_per_page)
    
    if search
      find(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"], :limit => @@results_per_page, :offset => offset)
    else
      find(:all, :limit => @@results_per_page, :offset => offset)
    end
  end
  
  def self.num_rows(search)
    num_rows = count(:all, :conditions => ["status = 'active' and nombre LIKE ?", "%#{search}%"])
    num_pages = (num_rows/@@results_per_page.to_f).ceil
    data = Hash.new
    data['rows'] = num_rows
    data['pages'] = num_pages
    return data
  end
  
  def self.get_afiliados(parent_id)
    find(:all, :conditions => ["status = 'active' and parent_id = ?", parent_id], :limit => 30)
  end

end

app/models/destino.rb
class Destino < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/hojadeatencion.rb
class Hojadeatencion < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :llamada
  has_many :signosvitale
end

app/models/llamada.rb
class Llamada < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :prioridad
  belongs_to :servicio
  belongs_to :statusllamada
  belongs_to :destino
  belongs_to :ambulance
  has_many   :bitacorallamada
  has_many   :hojadeatencion
  
  #accepts_nested_attributes_for :hojadeatencion
  
  validates :reporta, :reporte, :ubicacion, :presence => true
  
  before_save do |llamada|
      if llamada.id then
          original = Llamada.find(llamada.id)
          if original.statusllamada_id != llamada.statusllamada_id then
              BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
          end
      end
  end
  
  after_create do |llamada|
      BitacoraLlamada.create(:llamada_id => llamada.id, :statusllamada_id => llamada.statusllamada_id, :user_id => 1)
      @hoja = Hojadeatencion.create(:llamada_id => llamada.id)
      # I know this is ugly but I promess to fix it when I have more time
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
      Signosvitale.create(:hojadeatencion_id => @hoja.id)
  end
end

app/models/prioridad.rb
class Prioridad < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_one :llamada
  # attr_accessible :title, :body
end

app/models/signosvitale.rb
class Signosvitale < ActiveRecord::Base
  # attr_accessible :title, :body
    belongs_to :hojadeatencion
end

app/models/statusllamada.rb
class Statusllamada < ActiveRecord::Base
  has_many :llamada
  has_many :bitacorallamada
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  attr_accessible :username, :password

  def self.authenticate(username, password)
    find(:first, :conditions => ["username = ? and password = ?", "#{username}", "#{password}"])
  end
end

app/controllers/llamadas_controller.rb
class LlamadasController < ApplicationController
  before_filter :authenticate
  
  def index
    conditions = "statusllamada_id not in (7,9)"
    order = "id DESC"
    
    if params[:filter] then
      filter = params[:filter]
      case filter[:name]
        when 'status'
            conditions = "statusllamada_id = #{filter[:statusllamada_id]}"
        when 'servicio'
            conditions = conditions + " and servicio_id = #{filter[:servicio_id]}"
        when 'prioridad'
            conditions = conditions + " and prioridad_id = #{filter[:prioridad_id]}"
        when 'fecha'
            order = "id #{filter[:order]}"
        else
      end
    end
    @llamadas = Llamada.where(conditions).order(order)
    
    @statusllamadas = Statusllamada.all
    @servicios = Servicio.all
    @prioridads = Prioridad.all
  end

  def show
    @llamada = Llamada.find(params[:id])
    
    #if params[:view] == 'bitacora' then
    #  @bitacora = BitacoraLlamada.where("llamada_id = #{@llamada.id}")
    #end
    
    @cliente = Cliente.find(@llamada.cliente_id)
    @prioridads = Prioridad.all
    @servicios = Servicio.all
    @destinos = Destino.all
    @ambulances = Ambulance.all
    @statusllamadas = Statusllamada.all
    address = @cliente.direccion + ", " + @cliente.colonia + ", " + @cliente.ciudad + ", " + @cliente.estado + ", Mexico"
    @map = Geocoder.search(address)
    #@hojadeatencion = @llamada.hojadeatencion
  end

  def new
    $do = params[:do]
    search = params[:search]
    
    if search then
      
        $do = 'results'
        data = Cliente.num_rows(params[:search])
        $num_rows = data['rows']
        $num_pages = data['pages']
        @clientes = Cliente.search(params[:search], params[:page])
      
    elsif $do == 'create' then
        if params[:llamada] then
            @llamada = Llamada.new(params[:llamada])
        else
            @llamada = Llamada.new  
        end
        @cliente = Cliente.find(params[:cliente_id])
        @prioridads = Prioridad.all
        @servicios = Servicio.all
        @destinos = Destino.all
        @ambulances = Ambulance.all
        @statusllamadas = Statusllamada.all
        @llamada.cliente_id = params[:cliente_id]
    end
  end

  def create
    @llamada = Llamada.new(params[:llamada])
    if @llamada.valid?
      @llamada.save
      flash[:notice] = "La llamada fue registrada."
      redirect_to @llamada
    else
      flash[:error] = "Error porfavor verifica la info."
      redirect_to :action => 'new', :do => 'create', :cliente_id => params[:llamada][:cliente_id], :llamada => params[:llamada]
    end
  end

  def update
    @llamada = Llamada.find(params[:id])
    @llamada.update_attributes(params[:llamada])
    
    flash[:notice] = "Llamada Editada."
    
    if params[:redirect] == 'index'
      redirect_to :action => 'index'
    else
      redirect_to @llamada
    end
  end

  def destroy
    Llamada.update_all("status = 'deleted'", ["id = ?", params[:id]])
    
    flash[:notice] = "Llamada Eliminada."
    redirect_to :action => 'index'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
    @user = User.new
  end
  
  def process_login
    if user = User.authenticate(params[:username], params[:password])
        session[:id] = user.id
        session[:user_name] = user.nombre
        redirect_to session[:return_to] || root_url
    else
        flash[:error] = 'Invalid login.' 
        redirect_to :action => 'login'
      end
  end
  
  def logout
    reset_session
    session[:id] = nil
    flash[:notice] = "Logged out!"
    redirect_to :action => 'login' 
  end
end

app/helpers/ambulances_helper.rb
module AmbulancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/destinos_helper.rb
module DestinosHelper
end

app/helpers/llamadas_helper.rb
module LlamadasHelper
end

app/helpers/prioridads_helper.rb
module PrioridadsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/llamadas/_atencion.html.erb
<%= form_for([@llamada, @llamada.hojadeatencions.new]) do |f| %>
<div class="span span4">
      <h3>Via Aerea</h3>
      <div class="field">
        Permeable <br />
        <div class="field">
        <%= f.radio_button :permeable, 'si' %>SI Aspiracion
        <%= f.radio_button :permeable, 'no' %>NO Permeabilizacion Manual, Mecanica, blabla
      </div>
      </div>
      <h3>Ventilacion</h3>
      <div class="field">
        saturacion_inicial<br />
        <%= f.text_field :saturacion_inicial %>
      </div>
      <div class="field">
        saturacion_final  <br />
        <%= f.text_field :saturacion_final  %>
      </div>
      <h3>Circulacion</h3>
      <div class="field">
        coloracion_piel<br />
        <%= f.text_field :coloracion_piel %>
      </div>
      <div class="field">
        temperatura<br />
        <%= f.text_field :temperatura %>
      </div>
      <div class="field">
        llenado_capilar<br />
        <%= f.text_field :llenado_capilar %>
      </div>
      <div class="field">
        pulsos_perifericos<br />
        <%= f.text_field :pulsos_perifericos %>
      </div>
      <h3>Signos Vitales</h3>
      <table class="littlefields">
        <tr><td>Hora</td><td>FC</td><td>FR</td><td>T/A</td><td>TEMP</td></tr>
        <tr>
          <td><input type="text" name="sv[hora1]" size="3" style="width:26px;"></td>
          <td><input type="text" name="sv[fc1]" size="3"></td>
          <td><input type="text" name="sv[fr1]" size="3"></td>
          <td><input type="text" name="sv[ta1]" size="3"></td>
          <td><input type="text" name="sv[temp1]" size="3"></td>
        </tr>
        <tr>
          <td><input type="text" name="sv[hora2]" size="3"></td>
          <td><input type="text" name="sv[fc2]" size="3"></td>
          <td><input type="text" name="sv[fr2]" size="3"></td>
          <td><input type="text" name="sv[ta2]" size="3"></td>
          <td><input type="text" name="sv[temp2]" size="3"></td>
        </tr>
        <tr>
          <td><input type="text" name="sv[hora2]" size="3"></td>
          <td><input type="text" name="sv[fc2]" size="3"></td>
          <td><input type="text" name="sv[fr2]" size="3"></td>
          <td><input type="text" name="sv[ta2]" size="3"></td>
          <td><input type="text" name="sv[temp2]" size="3"></td>
        </tr>
      </table>
      
 </div>

<div class="span span4">     
      <h3>Estado Neurologico</h3>
      <div class="field">
        en_alerta<br />
        <%= f.text_field :en_alerta %>
      </div>
      <div class="field">
        en_verbal<br />
        <%= f.text_field :en_verbal %>
      </div>
      <div class="field">
        en_dolor<br />
        <%= f.text_field :en_dolor %>
      </div>
      <div class="field">
        en_inconciencia<br />
        <%= f.text_field :en_inconciencia %>
      </div>
      <h3>Estado Conciencia</h3>
       <div class="field">
        ec_persona<br />
        <%= f.text_field :ec_persona %>
      </div>
      <div class="field">
        ec_lugar<br />
        <%= f.text_field :ec_lugar %>
      </div>
      <div class="field">
        ec_tiempo <br />
        <%= f.text_field :ec_tiempo  %>
      </div>
      <div class="field">
        ec_ocular<br />
        <%= f.text_field :ec_ocular  %>
      </div>
      <div class="field">
        ec_verbal<br />
        <%= f.text_field :ec_verbal  %>
      </div>
      <div class="field">
        ec_motora <br />
        <%= f.text_field :ec_motora  %>
      </div>
      <div class="field">
        ec_clasgow <br />
        <%= f.text_field :ec_clasgow    %>
      </div>
</div>

<div class="span span4">    
      <h3>Historia Clinica</h3>
      <div class="field">
        hc_alergia<br />
        <%= f.text_field :hc_alergia %>
      </div>
      <div class="field">
        hc_patologia<br />
        <%= f.text_field :hc_patologia %>
      </div>
      <h3>Exploracion Fisica</h3>
      <div class="field">
        dolor<br />
        <%= f.text_field :dolor %>
      </div>
      <h3>Impresion Diagnostica</h3>
      <div class="field">
        indicaciones<br />
        <%= f.text_field :indicaciones %>
      </div>
      <div class="field">
        manejo<br />
        <%= f.text_field :manejo %>
      </div>
      <div class="field">
        medico<br />
        <%= f.text_field :medico %>
      </div>
      <%= f.submit :Guardar %>
</div>
<% end %>

app/views/llamadas/_cliente.html.erb
<%= form_tag 'new', :method => 'get', :class => 'well form-search' do %>
    <span id="page-title" class="lead space-right"><a href="?do=search&amp;t=clientes">Clientes</a></span>
    <%= text_field_tag :search, params[:search], :placeholder => 'escriba el criterio de búsqueda', :class => 'input-medium search-query' %>
    <!--<button type="submit" class="btn"><i class="icon-search"></i></button> -->
    <!--<button id="add-record" type="submit" class="btn"><i class="custom cus-add"></i></button> -->
    <%= submit_tag "Buscar", :name => nil %>
<% end %>

app/views/llamadas/_filtros.html.erb
<%= form_tag '', :method => 'get', :class => 'well form-search' do %>
<%

status, servicio, prioridad, fecha = false
statusllamada_id, servicio_id, prioridad_id, order = 0

if params[:filter] then
  filter = params[:filter]
  case params[:filter][:name]
    when 'status'
         status = true
         statusllamada_id = filter[:statusllamada_id]
    when 'servicio'
         servicio = true
         servicio_id = filter[:servicio_id]
    when 'prioridad'
         prioridad = true
         prioridad_id = filter[:prioridad_id]
    when 'fecha'
         fecha = true
         order = filter[:order]
  end
end
%>

<table>
  <tr>
      <td><%= radio_button_tag 'filter[name]', 'status', status %>Status</td>
      <td>
        <select name="filter[statusllamada_id]" id="status">
           <% @statusllamadas.each do |status| %><option value="<%= status.id %>" <%= 'selected' if statusllamada_id.to_i == (status.id).to_i %>><%= status.nombre %></option><% end %>
        </select>
      </td>

      <td><%= radio_button_tag 'filter[name]', 'servicio', servicio %>Servicio</td>
      <td>
        <select name="filter[servicio_id]" id="status">
            <% @servicios.each do |servicio| %>
                <option value="<%= servicio.id %>" <%= 'selected' if servicio_id.to_i == servicio.id.to_i %>><%= servicio.nombre %></option>
            <% end %>
        </select>
      </td>
  </tr>
  
  <tr>
      <td><%= radio_button_tag 'filter[name]', 'prioridad', prioridad %>Prioridad</td>
      <td>
          <table>
          <tbody>
            <tr>
            <% @prioridads.each do |prioridad| %>
            <td style="padding:10px;background-color:<%= prioridad.rgbcolor %>;">
              <input name="filter[prioridad_id]" type="radio" value="<%= prioridad.id %>" <%= 'checked="true"' if prioridad_id.to_i == prioridad.id.to_i %>><%= prioridad.nombre %>
            </td>
            <% end %>
           </tr>
          </tbody>
        </table>
      </td>

   <td><%= radio_button_tag 'filter[name]', 'fecha', fecha %>Fecha</td>
   <td>
      <select name="filter[order]" id="status">
         <option value="ASC" <%= 'selected' if order == 'ASC' %>>Ascendente</option>
         <option value="DESC" <%= 'selected' if order == 'DESC' %>>Descendente</option>
      </select>
    </td>
  </tr>
</table>
<%= submit_tag "Aplicar", :name => nil %>
<% end %>

app/views/llamadas/_form.html.erb
<%= form_for(@llamada) do |f| %>
  <% if @llamada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@llamada.errors.count, "error") %> prohibited this llamada from being saved:</h2>

      <ul>
      <% @llamada.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="span span4">
      <div class="field">
        Quién reporta <br />
        <%= f.text_field :reporta %>
      </div>
      <div class="field">
        Qué sucedió<br />
        <%= f.text_area :reporte %>
      </div>
      <div class="field">
        Ubicación del lesionado<br />
        <%= f.text_area :ubicacion %>
      </div>
      <div class="field">
        Teléfono<br />
        <%= f.text_field :telefono %>
      </div>
</div>

<div class="span span4">
      <h3>Datos del lesionado</h3>
      <div class="field">
        Nombre<br />
        <%= f.text_field :nombre %>
      </div>
      <div class="field">
        Apellido Paterno<br />
        <%= f.text_field :apaterno %>
      </div>
      <div class="field">
        Apellido Materno<br />
        <%= f.text_field :amaterno %>
      </div>
      <div class="field">
        Edad (en años)<br />
        <%= f.number_field :edad %>
      </div>
      <div class="field">
        <%= f.radio_button :sexo, 'masculino' %>Masculino
        <%= f.radio_button :sexo, 'femenino' %>Femenino
      </div>
</div>

<div class="span span4">    
      <div class="field">
        <%= f.label :servicio %><br />
        <select name="llamada[servicio_id]" id="status">
            <option value="0">---</option>
            <% @servicios.each do |servicio| %>
                <option value="<%= servicio.id %>" <%= 'selected' if servicio.id == @llamada.servicio_id %>><%= servicio.nombre %></option>
            <% end %>
        </select>
      </div>
      
      <div class="field">
        <%= f.label :destino %><br />
        <select name="llamada[destino_id]" id="destino">
            <option value="0">---</option>
            <% @destinos.each do |destino| %>
                <option value="<%= destino.id %>" <%= 'selected' if destino.id == @llamada.destino_id %>><%= destino.nombre %></option>
            <% end %>
          </select>
      </div>
      
      <div class="field">
        <%= f.label :status %><br />
          <select name="llamada[statusllamada_id]" id="status">
          <% @statusllamadas.each do |status| %><option value="<%= status.id %>" <%= 'selected' if status.id == @llamada.statusllamada_id %>><%= status.nombre %></option><% end %>
          </select>
      </div>
        
      <div class="field">
        <%= f.label :prioridad %><br />
        <table>
          <tbody>
            <tr>
            <% @prioridads.each do |prioridad| %>
            <td style="padding:10px;background-color:<%= prioridad.rgbcolor %>;">
              <input name="llamada[prioridad_id]" type="radio" value="<%= prioridad.id %>" <%= 'checked="true"' if prioridad.id == @llamada.prioridad_id %>><%= prioridad.nombre %>
            </td>
            <% end %>
           </tr>
          </tbody>
        </table>
      </div>
      
      <div class="field">
        <%= f.label 'Ambulancias Asignadas' %><br />
        <select name="llamada[ambulance_id]" id="ambulancia" multiple="true" size="5">
            <option value="0">---</option>
            <% @ambulances.each do |ambulance| %>
            <option value="<%= ambulance.id %>" <%= 'selected' if ambulance.id == @llamada.ambulance_id %>><%= ambulance.nombre %></option>
            <% end %>
          </select>
      </div>
      
      <div class="field">
        Costo<br />
        <%= f.text_field :costo %>
      </div>
      
      <%= f.hidden_field :cliente_id, :value => @llamada.cliente_id %>
      <div class="actions">
        <%= f.submit 'Guardar', :class => 'btn' %>
      </div>
</div>
<% end %>

app/views/llamadas/_map.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAzUbqULUkUSV-ICTh9kK3BuMXAIL21jD0&amp;sensor=false&v=3"></script>
<%
latitude = @map[0].latitude  # =>  25.4235607
longitude = @map[0].longitude  # =>  -100.9859354
address = @map[0].address  # =>  "Jose Maria la fragua 964, Zona Centro, 25000 Saltillo, Coahuila, Mexico"
%>
<script type="text/javascript">
      function initialize() 
      {
        var myLatlng = new google.maps.LatLng(<%= latitude %>, <%= longitude %>);
        var mapOptions = {
          center: myLatlng,
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),mapOptions);
        var marker = new google.maps.Marker({position: myLatlng, title:"Hector es el mas Mejor!"});
        marker.setMap(map);
      }
</script>
<b4/>
<h3>
  latitude: <%= latitude %>
  longitude: <%= longitude %>
  address: <%= address %>
</h3>
<div id="map_canvas"  style="background-color: rgb(229, 227, 223); height: 50%; width: 90%; overflow: auto; position: absolute;">
  hey Im here
</div>

app/views/llamadas/_nav_menu.html.erb
<div class="pull-right">
   <%= link_to 'Bitacora', llamada_bitacoras_path(@llamada), :class => 'btn' %>
   <%= link_to 'Hoja de Atencion', llamada_hojadeatencions_path(@llamada), :class => 'btn' %>
   <%= link_to 'Regresar', llamadas_path, :class => 'btn' %>
</div>

app/views/llamadas/_results_clientes.html.erb
<%
current = params[:page].to_i
if current == 0 then 
      current = 1
end
anterior = current.to_i - 1
siguiente = current.to_i + 1
%>
Clientes : <%= $num_rows %>
<div class="pull-right">
   <% if anterior > 0 %>
     <%= link_to 'Anterior', "?search=#{params[:search]}&page=#{anterior}", :class => 'btn' %>
   <% end %>
   <%= current %> de <%= $num_pages %>
   <% if current <  $num_pages %>
     <%= link_to 'Siguiente', "?search=#{params[:search]}&page=#{siguiente}", :class => 'btn' %>
   <% end %>
</div>
<br/>
<ul>
  <% @clientes.each do |cliente| %>
  <li>
    <a class="profile-link" href="?do=create&amp;cliente_id=<%= cliente.id %>">
      <i class="custom cus-user"></i><%= cliente.nombre %> (<%= cliente.id %>)
    </a>
  </li>
  <% end %>
</ul>

app/views/llamadas/_show_cliente.html.erb
<div class="span span4">

<div class="field">
  <b>Cliente:</b>
  <%= @cliente.id %>
</div>

<% if @cliente.parent_id %>
<div class="field">
  <b>Membresía:</b>
  <%= @cliente.parent_id %>
</div>
<% end %>

<div class="field">
  <%= @cliente.nombre %>
</div>
<br/>
<div class="field">
  <%= @cliente.direccion %>
</div>
<div class="field">
  Colonia
  <%= @cliente.colonia %>
</div>
<div class="field">
  Entre 
  <%= @cliente.entre_calles %>
</div>
<div class="field">
  Código Postal 
  <%= @cliente.cp %>
</div>

<br/>

<div class="field">
  <%= @cliente.telefono %>
</div>
<div class="field">
  <%= @cliente.ciudad %>
</div>
<div class="field">
  <%= @cliente.estado %>
</div>

<br/>
<div class="field">
  <b>Razón Social:</b>
  <%= @cliente.razon_social %>
</div>

<div class="field">
  <b>RFC:</b>
  <%= @cliente.rfc %>
</div>

<div class="field">
  <b>Avisar:</b>
  <%= @cliente.avisar %>
</div>

<div class="field">
  <b>Servicio Médico:</b>
  <%= @cliente.servicio_medico %>
</div>

<div class="field">
  <b>Afiliación:</b>
  <%= @cliente.afiliacion %>
</div>

<div class="field">
  <b>Tipo Sanguíneo:</b>
  <%= @cliente.tipo_sanguineo %>
</div>

<div class="field">
  <b>Fecha de Nacimiento:</b>
  <%= @cliente.fecha_nacimiento %>
</div>

<div class="field">
  <b>Padecimientos:</b>
  <%= @cliente.padecimientos %>
</div>

<div class="field">
  <b>Alergias:</b>
  <%= @cliente.alergias %>
</div>

</div>

app/views/llamadas/index.html.erb
<h3>Filtros</h3>
<div id="filtros">
    <%= render 'filtros' %>
</div>

<div class="pull-right">
        <%= link_to 'Registrar Llamada', new_llamada_path, :class => 'btn' %>
</div>

<h2>Servicios Activos <%= @llamadas.count %></h2>

<table  cellspacing="0" cellpadding="4" border="0">
  <thead>
  <tr>
    <th>ID</th>
    <th>Fecha</th>
    <th>Tiempo Transcurrido</th>
    <th>Membresía</th>
    <th>Ambulancia</th>
    <th>Servicio</th>
    <th>Prioridad</th>
    <th>Status</th>
  </tr>
  </thead>

<% @llamadas.each do |llamada| %>
  <%
    now = Time.new
    predays = (now - llamada.created_at)/1.day
    days = predays.floor
    prehours = (predays - days)*24
    hours = prehours.floor
    preminutes = (prehours-hours)*60
    minutos = preminutes.floor
    d = llamada.created_at
  %>
  <tr>
    <td><%=link_to llamada.id, llamada, :class => 'btn' %></td>
    <td><%= d.strftime("%d/%b/%Y %I:%M%p") %></td>
    <td><%= days %> dias, <%= hours %>H <%= minutos %>M</td>
    <td><%= llamada.cliente.nombre %></td>
    <td><%= llamada.ambulance.nombre if !llamada.ambulance.nil? %></td>
    <td><%= llamada.servicio.nombre if !llamada.servicio.nil? %></td>
    <td>
      <% if !llamada.prioridad.nil? then %>
        <div style="padding:10px;background-color:<%= llamada.prioridad.rgbcolor %>"><%= llamada.prioridad.nombre %></div>
      <% end %>
    </td>
    <td>
      <%= form_for(llamada) do |f| %>
           <select name="llamada[statusllamada_id]" id="status">
              <% @statusllamadas.each do |status| %><option value="<%= status.id %>" <%= 'selected' if status.id == llamada.statusllamada_id %>><%= status.nombre %></option><% end %>
          </select>
          <input type="hidden" name="redirect" value="index" />
          <%= f.submit 'update' %>
      <% end %>
    </td>
  </tr>
<% end %>

</table>

app/views/llamadas/new.html.erb
<div class="pull-right">
        <%= link_to 'Regresar', llamadas_path, :class => 'btn' %>
</div>

<h2>Captura de Llamada</h2>

<% if $do == 'create' %>
<div class="row">
   <%= render 'show_cliente' %>
   <%= render 'form' %>
</div>
<% elsif $do == 'results'  %>

    <%= render 'cliente' %>
    <%= render 'results_clientes' %>

<% else %>
    <%= render 'cliente' %>

<%  end %>

app/views/llamadas/show.html.erb
<%= render 'nav_menu' %>

<h2>Llamada</h2>

<div class="row">
       <%= render 'show_cliente' %>
       <%= render 'form' %>
</div>
<div style="min-height: 500px;"><br/><br/><%= render :partial => 'layouts/map' %></div>